[versions]
agp = "8.5.0"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.22"
coreKtx = "1.13.1"
junit = "4.13.2" # Standard JUnit 4
appcompat = "1.6.1"
material = "1.11.0"
coroutines = "1.8.1"
lifecycle = "2.7.0"

androidxTestExt = "1.1.5"
espressoCore = "3.5.1"
mockkVersion = "1.13.10"
robolectricVersion = "4.12.2"

roomVersion = "2.6.1"


retrofitVersion = "2.9.0"
moshiVersion = "1.15.1"
okHttpVersion = "4.12.0"

serializationJsonVersion = "1.6.0"
retrofitSerializationConverterVersion = "1.0.0"

workVersion = "2.9.0"

hiltAndroidVersion = "2.51.1"
hiltExtVersion = "1.2.0" # For Hilt Extensions (WorkManager)

[libraries]

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

sqlite-sqlcipher = { group = "net.zetetic", name = "android-database-sqlcipher", version = "4.4.0" }

version.ref = "roomVersion"

androidx-sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "roomVersion" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJsonVersion" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectricVersion" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofitVersion" }
retrofit-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitSerializationConverterVersion" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttpVersion" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiVersion" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshiVersion" }

androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workVersion" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExtVersion" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExtVersion" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroidVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroidVersion" }

[bundles]

database = [
"androidx-room-runtime",
"androidx-room-ktx"
]
kotlin-coroutines = [
"kotlinx-coroutines-core",
"kotlinx-coroutines-android"
]
androidx-lifecycle = [
"androidx-lifecycle-runtime-ktx",
"androidx-lifecycle-viewmodel-ktx"
]
networking = [
"retrofit",
"converter-moshi",
"retrofit-serialization-converter",
"logging-interceptor",
"moshi-kotlin"
]

di-hilt = [
"hilt-android"
]
work-manager = [
"androidx-work-runtime-ktx",
"hilt-work"
]
